export const fontOptions = [
    { label: 'Inter (Default)', value: 'sans', fontFamily: 'var(--font-inter), sans-serif' },
    { label: 'Roboto', value: 'roboto', fontFamily: 'Roboto, sans-serif' },
    { label: 'Open Sans', value: 'open-sans', fontFamily: '"Open Sans", sans-serif' },
    { label: 'Montserrat', value: 'montserrat', fontFamily: 'Montserrat, sans-serif' },
    { label: 'Lato', value: 'lato', fontFamily: 'Lato, sans-serif' },
    { label: 'Poppins', value: 'poppins', fontFamily: 'Poppins, sans-serif' },
    { label: 'Merriweather', value: 'merriweather', fontFamily: 'Merriweather, serif' },
    { label: 'Playfair Display', value: 'playfair', fontFamily: '"Playfair Display", serif' },
    { label: 'Oswald', value: 'oswald', fontFamily: 'Oswald, sans-serif' },
    { label: 'Raleway', value: 'raleway', fontFamily: 'Raleway, sans-serif' },
    { label: 'Nunito', value: 'nunito', fontFamily: 'Nunito, sans-serif' },
    { label: 'PT Sans', value: 'pt-sans', fontFamily: '"PT Sans", sans-serif' },
    { label: 'Rubik', value: 'rubik', fontFamily: 'Rubik, sans-serif' },
    { label: 'Work Sans', value: 'work-sans', fontFamily: '"Work Sans", sans-serif' },
    { label: 'Quicksand', value: 'quicksand', fontFamily: 'Quicksand, sans-serif' },
    { label: 'Karla', value: 'karla', fontFamily: 'Karla, sans-serif' },
    { label: 'Lora', value: 'lora', fontFamily: 'Lora, serif' },
    { label: 'Fira Sans', value: 'fira-sans', fontFamily: '"Fira Sans", sans-serif' },
    { label: 'Mulish', value: 'mulish', fontFamily: 'Mulish, sans-serif' },
    { label: 'Titillium Web', value: 'titillium-web', fontFamily: '"Titillium Web", sans-serif' },
    { label: 'Ubuntu', value: 'ubuntu', fontFamily: 'Ubuntu, sans-serif' },
    { label: 'Bebas Neue', value: 'bebas-neue', fontFamily: '"Bebas Neue", sans-serif' },
    { label: 'Anton', value: 'anton', fontFamily: 'Anton, sans-serif' },
    { label: 'Cabin', value: 'cabin', fontFamily: 'Cabin, sans-serif' },
    { label: 'Dancing Script', value: 'dancing-script', fontFamily: '"Dancing Script", cursive' },
    { label: 'Source Sans Pro', value: 'source-sans-pro', fontFamily: '"Source Sans Pro", sans-serif' },
    { label: 'Oxygen', value: 'oxygen', fontFamily: 'Oxygen, sans-serif' },
    { label: 'Arvo', value: 'arvo', fontFamily: 'Arvo, serif' },
    { label: 'Noto Sans', value: 'noto-sans', fontFamily: '"Noto Sans", sans-serif' },
    { label: 'Noto Serif', value: 'noto-serif', fontFamily: '"Noto Serif", serif' },
    { label: 'Bitter', value: 'bitter', fontFamily: 'Bitter, serif' },
    { label: 'Crimson Text', value: 'crimson-text', fontFamily: '"Crimson Text", serif' },
    { label: 'Dosis', value: 'dosis', fontFamily: 'Dosis, sans-serif' },
    { label: 'Josefin Sans', value: 'josefin-sans', fontFamily: '"Josefin Sans", sans-serif' },
    { label: 'Libre Baskerville', value: 'libre-baskerville', fontFamily: '"Libre Baskerville", serif' },
    { label: 'Mukta', value: 'mukta', fontFamily: 'Mukta, sans-serif' },
    { label: 'Inconsolata', value: 'inconsolata', fontFamily: 'Inconsolata, monospace' },
    { label: 'Pacifico', value: 'pacifico', fontFamily: 'Pacifico, cursive' },
    { label: 'Shadows Into Light', value: 'shadows-into-light', fontFamily: '"Shadows Into Light", cursive' },
    { label: 'Indie Flower', value: 'indie-flower', fontFamily: '"Indie Flower", cursive' },
    { label: 'Abril Fatface', value: 'abril-fatface', fontFamily: '"Abril Fatface", cursive' },
    { label: 'Comfortaa', value: 'comfortaa', fontFamily: 'Comfortaa, cursive' },
    { label: 'Exo 2', value: 'exo-2', fontFamily: '"Exo 2", sans-serif' },
    { label: 'Hind', value: 'hind', fontFamily: 'Hind, sans-serif' },
    { label: 'Manrope', value: 'manrope', fontFamily: 'Manrope, sans-serif' },
    { label: 'Barlow', value: 'barlow', fontFamily: 'Barlow, sans-serif' },
    { label: 'Heebo', value: 'heebo', fontFamily: 'Heebo, sans-serif' },
    { label: 'DM Sans', value: 'dm-sans', fontFamily: '"DM Sans", sans-serif' },
    { label: 'Space Grotesk', value: 'space-grotesk', fontFamily: '"Space Grotesk", sans-serif' },
    { label: 'Outfit', value: 'outfit', fontFamily: 'Outfit, sans-serif' },
    { label: 'Syncopate', value: 'syncopate', fontFamily: 'Syncopate, sans-serif' },
    { label: 'Syne', value: 'syne', fontFamily: 'Syne, sans-serif' },
    { label: 'Clash Display', value: 'clash-display', fontFamily: '"Clash Display", sans-serif' },
    { label: 'General Sans', value: 'general-sans', fontFamily: '"General Sans", sans-serif' },
    { label: 'Satoshi', value: 'satoshi', fontFamily: 'Satoshi, sans-serif' },
    { label: 'Monospace', value: 'mono', fontFamily: 'ui-monospace, monospace' },
]

export const getFontFamily = (value: string) => {
    const font = fontOptions.find(f => f.value === value)
    return font ? font.fontFamily : 'inherit'
}
